### ISSUE TITLE
Error when trying to run the example in the first benchmark_tiny.sh

### ISSUE THREAD

**Issue by binbinbinv** [zrqiao/NeuralPLexer#34]
* PIGT version:
* Python version: 3.10
* Operating System: Ubuntu 22.04

### Description

I'm trying to run the first example in benchmark_tiny.sh, but I'm getting an error running the example commands after successfully following the instructions to install the environment, I've searched for ways to try to fix this but can't at the moment.

### What I Did

```
git clone https://github.com/zrqiao/NeuralPLexer.git
cd NeuralPLexer
make environment
conda activate neuralplexer_dev
make install
unzip neuralplexermodels_downstream_datasets_predictions.zip
```

Everything's fine up to now.

Then I ran the code of the first example in  benchmark_tiny.sh:

'''
mkdir results
neuralplexer-inference --task structure_prediction_benchmarking --input-receptor neuralplexermodels_downstream_datasets_predictions/downstream_test_datasets/complex_structure_prediction/pocketminer/ --input-ligand neuralplexermodels_downstream_datasets_predictions/downstream_test_datasets/complex_structure_prediction/pocketminer/ --out-path results/tiny_run_complexpred_benchmark_post2019targets  --input-template neuralplexermodels_downstream_datasets_predictions/downstream_test_datasets/complex_structure_prediction/af2templates_colabfold_predictions_Feb2023/pocketminer+post2019targets/set_512_1234_pred032223 --model-checkpoint neuralplexermodels_downstream_datasets_predictions/models/complex_structure_prediction.ckpt --n-samples 2 --chunk-size 2 --start-time 1.0 --num-steps=40 --cuda --sampler=langevin_simulated_annealing --csv-path neuralplexermodels_downstream_datasets_predictions/downstream_test_datasets/complex_structure_prediction/pocketminer/test_index.csv --template-id=3 --use-template
'''

It presents several problems:

#### 1st Problems with calling pytorch_lightning to fully load model parameters of 
neuralplexermodels_downstream_datasets_predictions/models/complex_structure_prediction.ckpt
![image](https://github.com/zrqiao/NeuralPLexer/assets/106214575/5a9c36fa-ac4f-4607-bf69-73318c7e3415)

#### 2nd Could not load pretrained MHT weights, skipping
![image](https://github.com/zrqiao/NeuralPLexer/assets/106214575/a15d298c-3576-4041-9870-aacef079ca53)

#### 3rd local variable 'res_df' referenced before assignment
![image](https://github.com/zrqiao/NeuralPLexer/assets/106214575/63e24eab-b073-4a13-890b-832ee44157f0)

**Comment by Nireus-lgx** [comment]
> * PIGT version:
> * Python version: 3.10
> * Operating System: Ubuntu 22.04
> 
> ### Description
> I'm trying to run the first example in benchmark_tiny.sh, but I'm getting an error running the example commands after successfully following the instructions to install the environment, I've searched for ways to try to fix this but can't at the moment.
> 
> ### What I Did
> ```
> git clone https://github.com/zrqiao/NeuralPLexer.git
> cd NeuralPLexer
> make environment
> conda activate neuralplexer_dev
> make install
> unzip neuralplexermodels_downstream_datasets_predictions.zip
> ```
> 
> Everything's fine up to now.
> 
> Then I ran the code of the first example in benchmark_tiny.sh:
> 
> ''' mkdir results neuralplexer-inference --task structure_prediction_benchmarking --input-receptor neuralplexermodels_downstream_datasets_predictions/downstream_test_datasets/complex_structure_prediction/pocketminer/ --input-ligand neuralplexermodels_downstream_datasets_predictions/downstream_test_datasets/complex_structure_prediction/pocketminer/ --out-path results/tiny_run_complexpred_benchmark_post2019targets --input-template neuralplexermodels_downstream_datasets_predictions/downstream_test_datasets/complex_structure_prediction/af2templates_colabfold_predictions_Feb2023/pocketminer+post2019targets/set_512_1234_pred032223 --model-checkpoint neuralplexermodels_downstream_datasets_predictions/models/complex_structure_prediction.ckpt --n-samples 2 --chunk-size 2 --start-time 1.0 --num-steps=40 --cuda --sampler=langevin_simulated_annealing --csv-path neuralplexermodels_downstream_datasets_predictions/downstream_test_datasets/complex_structure_prediction/pocketminer/test_index.csv --template-id=3 --use-template '''
> 
> It presents several problems:
> 
> #### 1st Problems with calling pytorch_lightning to fully load model parameters of
> neuralplexermodels_downstream_datasets_predictions/models/complex_structure_prediction.ckpt ![image](https://private-user-images.githubusercontent.com/106214575/329484387-5a9c36fa-ac4f-4607-bf69-73318c7e3415.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTg4MzgsIm5iZiI6MTcxNTkxODUzOCwicGF0aCI6Ii8xMDYyMTQ1NzUvMzI5NDg0Mzg3LTVhOWMzNmZhLWFjNGYtNDYwNy1iZjY5LTczMzE4YzdlMzQxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwNDAyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjI2NmNhNjI4ZTBhNzMzZjNmZWZlOGMzYTQxMTA4ZTFkNTRhYmRlMDQ2YzY1NmNlYTFiODM1OTNkMzJhZWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sE9XgcK1SoazvEFluj6TtyyDcyGdRICCVGAtVmnAMS4)
> 
> #### 2nd Could not load pretrained MHT weights, skipping
> ![image](https://private-user-images.githubusercontent.com/106214575/329485155-a15d298c-3576-4041-9870-aacef079ca53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTg4MzgsIm5iZiI6MTcxNTkxODUzOCwicGF0aCI6Ii8xMDYyMTQ1NzUvMzI5NDg1MTU1LWExNWQyOThjLTM1NzYtNDA0MS05ODcwLWFhY2VmMDc5Y2E1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwNDAyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjZjZjRhN2UxZWY3ODdlYzAwNTJhYWZjZmVkNmRkZWM3MTM0Yjc0YWU1Y2Y0ZWI5OTAxZmIyMjIwMDEzZjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LIJU-S5gYtS_nQGi1CGa_KzHAeJ437UD-9R1rz7GGjg)
> 
> #### 3rd local variable 'res_df' referenced before assignment
> ![image](https://private-user-images.githubusercontent.com/106214575/329485322-63e24eab-b073-4a13-890b-832ee44157f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MTg4MzgsIm5iZiI6MTcxNTkxODUzOCwicGF0aCI6Ii8xMDYyMTQ1NzUvMzI5NDg1MzIyLTYzZTI0ZWFiLWIwNzMtNGExMy04OTBiLTgzMmVlNDQxNTdmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwNDAyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzE5MDRjYTY2ZTlhZWNjOTMwMTgwMzJhZmYyZjdkZmYyYTg3NzA4MDk1MTljYzZjNzFlYTJhMzU5NTRlYmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.APZlhUNH9LGN0RIT6LDC8PHzIlmnd8rU1F8gC7wumd0)

hi,i had the same error with you. Did you solved this?

**Comment by Nireus-lgx** [comment]
hi,i had the same error with you. Did you solved this?

**Comment by binbinbinv** [comment]
> hi,i had the same error with you. Did you solved this?

I installed Docker to run this Dockerfile, but the results cannot show the secondary structure in the pymol, maybe there is still some errors but I don't know what it is.

**Comment by Nireus-lgx** [comment]
> > hi,i had the same error with you. Did you solved this?
> 
> I installed Docker to run this Dockerfile, but the results cannot show the secondary structure in the pymol, maybe there is still some errors but I don't know what it is.

After installing the Dockerfile, when I start the Docker container, it automatically exits directly, and the command shows that the actual running command is: "conda run -n NeuralPLexer...". 
The steps for me to install dockerfile : 1.docker build -t neuralplexer .   2.docker run <id>
Can you tell me how it was solved? Thank you very much.?

**Comment by binbinbinv** [comment]
> > > hi,i had the same error with you. Did you solved this?
> > 
> > 
> > I installed Docker to run this Dockerfile, but the results cannot show the secondary structure in the pymol, maybe there is still some errors but I don't know what it is.
> 
> After installing the Dockerfile, when I start the Docker container, it automatically exits directly, and the command shows that the actual running command is: "conda run -n NeuralPLexer...". The steps for me to install dockerfile : 1.docker build -t neuralplexer . 2.docker run Can you tell me how it was solved? Thank you very much.?

If you installed the Docker in the right way, you can use the command below to run the Docker in the terminal:
docker run -it --entrypoint /bin/bash neuralplexer
Maybe you need to mount some file paths while running Docker, you can learn the basics of using Docker at bilibili or youtube.

**Comment by Nireus-lgx** [comment]
> > > > hi,i had the same error with you. Did you solved this?
> > > 
> > > 
> > > I installed Docker to run this Dockerfile, but the results cannot show the secondary structure in the pymol, maybe there is still some errors but I don't know what it is.
> > 
> > 
> > After installing the Dockerfile, when I start the Docker container, it automatically exits directly, and the command shows that the actual running command is: "conda run -n NeuralPLexer...". The steps for me to install dockerfile : 1.docker build -t neuralplexer . 2.docker run Can you tell me how it was solved? Thank you very much.?
> 
> If you installed the Docker in the right way, you can use the command below to run the Docker in the terminal: docker run -it --entrypoint /bin/bash neuralplexer Maybe you need to mount some file paths while running Docker, you can learn the basics of using Docker at bilibili or youtube.

This worked for me! thank you very much!

**Comment by Nireus-lgx** [comment]
> > > > > hi,i had the same error with you. Did you solved this?
> > > > 
> > > > 
> > > > I installed Docker to run this Dockerfile, but the results cannot show the secondary structure in the pymol, maybe there is still some errors but I don't know what it is.
> > > 
> > > 
> > > After installing the Dockerfile, when I start the Docker container, it automatically exits directly, and the command shows that the actual running command is: "conda run -n NeuralPLexer...". The steps for me to install dockerfile : 1.docker build -t neuralplexer . 2.docker run Can you tell me how it was solved? Thank you very much.?
> > 
> > 
> > If you installed the Docker in the right way, you can use the command below to run the Docker in the terminal: docker run -it --entrypoint /bin/bash neuralplexer Maybe you need to mount some file paths while running Docker, you can learn the basics of using Docker at bilibili or youtube.
> 
> This worked for me! thank you very much!

寄……运行还是出现“Could not load pretrained MHT weights, skipping”等问题，大佬能给一下你的Dockerfile和环境文件(NeuralPLexer-requirements.txt、NeuralPLexer.yml)吗？

**Comment by binbinbinv** [comment]
> > > > > > hi,i had the same error with you. Did you solved this?
> > > > > 
> > > > > 
> > > > > I installed Docker to run this Dockerfile, but the results cannot show the secondary structure in the pymol, maybe there is still some errors but I don't know what it is.
> > > > 
> > > > 
> > > > After installing the Dockerfile, when I start the Docker container, it automatically exits directly, and the command shows that the actual running command is: "conda run -n NeuralPLexer...". The steps for me to install dockerfile : 1.docker build -t neuralplexer . 2.docker run Can you tell me how it was solved? Thank you very much.?
> > > 
> > > 
> > > If you installed the Docker in the right way, you can use the command below to run the Docker in the terminal: docker run -it --entrypoint /bin/bash neuralplexer Maybe you need to mount some file paths while running Docker, you can learn the basics of using Docker at bilibili or youtube.
> > 
> > 
> > This worked for me! thank you very much!
> 
> 寄……运行还是出现“Could not load pretrained MHT weights, skipping”等问题，大佬能给一下你的Dockerfile和环境文件(NeuralPLexer-requirements.txt、NeuralPLexer.yml)吗？

As I understand it, even if there is a "Could not load pretrained MHT weights, skipping" problem, the model still works fine, see:
https://github.com/zrqiao/NeuralPLexer/issues/14#issuecomment-2041202419

**Comment by Nireus-lgx** [comment]
> > > > > > > hi,i had the same error with you. Did you solved this?
> > > > > > 
> > > > > > 
> > > > > > I installed Docker to run this Dockerfile, but the results cannot show the secondary structure in the pymol, maybe there is still some errors but I don't know what it is.
> > > > > 
> > > > > 
> > > > > After installing the Dockerfile, when I start the Docker container, it automatically exits directly, and the command shows that the actual running command is: "conda run -n NeuralPLexer...". The steps for me to install dockerfile : 1.docker build -t neuralplexer . 2.docker run Can you tell me how it was solved? Thank you very much.?
> > > > 
> > > > 
> > > > If you installed the Docker in the right way, you can use the command below to run the Docker in the terminal: docker run -it --entrypoint /bin/bash neuralplexer Maybe you need to mount some file paths while running Docker, you can learn the basics of using Docker at bilibili or youtube.
> > > 
> > > 
> > > This worked for me! thank you very much!
> > 
> > 
> > 寄……运行还是出现“Could not load pretrained MHT weights, skipping”等问题，大佬能给一下你的Dockerfile和环境文件(NeuralPLexer-requirements.txt、NeuralPLexer.yml)吗？
> 
> As I understand it, even if there is a "Could not load pretrained MHT weights, skipping" problem, the model still works fine, see: [#14 (comment)](https://github.com/zrqiao/NeuralPLexer/issues/14#issuecomment-2041202419)

ಥ_ಥA new error has appeared. Have you met it?:
Traceback (most recent call last):
  File "/opt/conda/envs/NeuralPLexer/bin/neuralplexer-inference", line 33, in <module>
    sys.exit(load_entry_point('neuralplexer', 'console_scripts', 'neuralplexer-inference')())
  File "/NeuralPLexer/neuralplexer/inference.py", line 688, in main
    raise NotImplementedError
NotImplementedError

**Comment by Nireus-lgx** [comment]
> > > > > > > > hi,i had the same error with you. Did you solved this?
> > > > > > > 
> > > > > > > 
> > > > > > > I installed Docker to run this Dockerfile, but the results cannot show the secondary structure in the pymol, maybe there is still some errors but I don't know what it is.
> > > > > > 
> > > > > > 
> > > > > > After installing the Dockerfile, when I start the Docker container, it automatically exits directly, and the command shows that the actual running command is: "conda run -n NeuralPLexer...". The steps for me to install dockerfile : 1.docker build -t neuralplexer . 2.docker run Can you tell me how it was solved? Thank you very much.?
> > > > > 
> > > > > 
> > > > > If you installed the Docker in the right way, you can use the command below to run the Docker in the terminal: docker run -it --entrypoint /bin/bash neuralplexer Maybe you need to mount some file paths while running Docker, you can learn the basics of using Docker at bilibili or youtube.
> > > > 
> > > > 
> > > > This worked for me! thank you very much!
> > > 
> > > 
> > > 寄……运行还是出现“Could not load pretrained MHT weights, skipping”等问题，大佬能给一下你的Dockerfile和环境文件(NeuralPLexer-requirements.txt、NeuralPLexer.yml)吗？
> > 
> > 
> > As I understand it, even if there is a "Could not load pretrained MHT weights, skipping" problem, the model still works fine, see: [#14 (comment)](https://github.com/zrqiao/NeuralPLexer/issues/14#issuecomment-2041202419)
> 
> ಥ_ಥA new error has appeared. Have you met it?: Traceback (most recent call last): File "/opt/conda/envs/NeuralPLexer/bin/neuralplexer-inference", line 33, in sys.exit(load_entry_point('neuralplexer', 'console_scripts', 'neuralplexer-inference')()) File "/NeuralPLexer/neuralplexer/inference.py", line 688, in main raise NotImplementedError NotImplementedError

I have solved it because the input parameter format does not meet the requirements. Thank you very much for your valuable help!
